#!/bin/bash

SSHOPT="-i $HOME/.ssh/flink-cluster.pem -o StrictHostKeyChecking=no"

### Modify /etc/hosts ###

# get master ip
echo "$(ifconfig | grep Bcast | cut -d : -f 2 | cut -d B -f 1) jkmaster" > temphosts

# get slave ip
#hdfs dfsadmin -report | grep Name: | cut -d : -f 2 | sed 's/ //g' > slaves

i=1
for slave in $(cat slaves); do
	echo "$slave slave$i" >> temphosts
	i=$((i+1))
done 

sudo bash -c "cat temphosts >> /etc/hosts"

if [[ ! -e ~/.ssh/id_rsa ]]; then
	ssh-keygen -t rsa -P ""
fi

for slave in $(cat slaves); do
	scp $SSHOPT temphosts $slave:~
	ssh $SSHOPT $slave "sudo bash -c \"cat temphosts >> /etc/hosts\"; mkdir -p ~/DODO; rm ~/temphosts"
	scp $SSHOPT -r flink-1.1.3 $slave:~/DODO/
	cat ~/.ssh/id_rsa.pub | ssh $SSHOPT ubuntu@$slave "mkdir -p ~/.ssh && cat >>  ~/.ssh/authorized_keys"
done

rm temphosts
#rm slaves

#echo "export HADOOP_CONF_DIR=/etc/hadoop/conf" >> $HOME/.zshrc
echo "Type 'source ~/.zshrc'!"

