#!/bin/zsh

PACK_NAME=DODO

function echo_help() {
	echo "Usage:"
	echo "./pack_upload [-e] [2|3]"
	echo "Option:"
	echo "-e: package is already existed"
	exit 1
}

function do_pack() {
	if [[ -d $PACK_NAME ]]; then
		rm -r $PACK_NAME
	fi
	mkdir -p $PACK_NAME/util-tool/target
	mkdir -p $PACK_NAME/flink-example/target
	cp util-tool/target/util-tool-1.0-SNAPSHOT.jar $PACK_NAME/util-tool/target
	cp -r flink-1.1.3 $PACK_NAME/
	cp -r kafka_2.11-0.9.0.1 $PACK_NAME/
	cp measure stop_measure run rerun go init $PACK_NAME/
	cp flink-example/target/flink-example-0.1.jar $PACK_NAME/flink-example/target
	tar zcvf $PACK_NAME.tar.gz $PACK_NAME
}

#####################
#### in ~/.zshrc ####
# export AWS_USERNAME="ubuntu"
# export AWS_MASTER="ec2-ip.eu-west-1.compute.amazonaws.com"
# function sshx() {
# 	ssh -i ~/.ssh/flink-cluster.pem -ND 8157 $AWS_USERNAME@$AWS_MASTER
# }
# function saws() {
# 	ssh -i ~/.ssh/flink-cluster.pem $AWS_USERNAME@$AWS_MASTER $1
# }
# function scpi() {
# 	local AWS_FILE=`echo $2 | sed -e "s,${HOME},/home/hadoop,g"`
# 	scp -i ~/.ssh/flink-cluster.pem $1 $AWS_USERNAME@$AWS_MASTER:$AWS_FILE
# }
#####################

if [[ $# -eq 0 ]]; then
	do_pack
	SCPI=scpi
	SAWS=saws
elif [[ $# -eq 1 ]]; then
	if [[ $1 == "2" ]]; then
		do_pack
		SCPI=scpi2
		SAWS=saws2
	elif [[ $1 == "3" ]]; then
		do_pack
		SCPI=scpi3
		SAWS=saws3
	elif [[ $1 == "-e" ]]; then
		SCPI=scpi
		SAWS=saws
	else
		echo_help
	fi
elif [[ $# -eq 2 ]]; then
	if [[ ($1 == "2" && $2 == "-e") || ($1 == "-e" && $2 == "2") ]]; then
		SCPI=scpi2
		SAWS=saws2
	elif [[ ($1 == "3" && $2 == "-e") || ($1 == "-e" && $2 == "3") ]]; then
		SCPI=scpi3
		SAWS=saws3
	else
		echo_help
	fi
else
	echo_help
fi

source $HOME/.zshrc

$SCPI ~/.mytaste/ut
$SCPI $PACK_NAME.tar.gz
$SAWS "tar zxf $PACK_NAME.tar.gz; mkdir -p /home/$AWS_USERNAME/.aws; exit"
$SCPI $HOME/.ssh/flink-cluster.pem ~/.ssh/
$SCPI $HOME/.aws/credentials ~/.aws/

