#!/bin/zsh

if [[ $# -lt 2 ]]; then
	echo "You must give two arguments!"
	echo "./rerun LBOUND HBOUND"
	exit 1
fi

LBOUND=$1
HBOUND=$2
FLINKDIR=flink-1.1.3

./stop-measure

# stop flink
cd $FLINKDIR
#bin/stop-cluster.sh
for appid in `yarn application -list | grep application_ | cut -d ' ' -f 1 | awk '{print $1}'`; do
	yarn application -kill $appid
done
cd ..

./run.sh $LBOUND $HBOUND

