#!/bin/zsh

if [[ $# -eq 1 ]]; then
	LBOUND=$1
	UBOUND=$1
elif [[ $# -eq 2 ]]; then
	LBOUND=$1
	UBOUND=$2
else
	echo "You must give one or two arguments!"
	echo "./run lambda"
	echo "./run LBOUND UBOUND"
	exit 1
fi

mkdir -p msg-logs
if [[ -e ~/MessageController.log ]]; then
	rm ~/MessageController.log
fi

# start flink
cd flink-1.1.3
#bin/start-cluster.sh
bin/yarn-session.sh -n 5 -jm 1024 -tm 4096 &
sleep 20
cd ..

# run benckmark
for (( i=$LBOUND; i<=$UBOUND; i=i+200 )) do
	./measure $i --S3
	sleep 2400
	./stop_measure
	mv ~/MessageController.log msg-logs/msg$i.log
	sleep 15
done

# stop flink
cd flink-1.1.3
#bin/stop-cluster.sh
for appid in `yarn application -list | grep application_ | cut -d ' ' -f 1 | awk '{print $1}'`; do
	yarn application -kill $appid
done
cd ..

