#!/usr/bin/env python2

import os
import sys
import subprocess

if len(sys.argv) > 1:
    logdir = sys.argv[1]
else:
    logdir = "msg-logs"

if (not os.path.exists(logdir)):
    print "no such log dir!"
    exit()

for dirname, dirnames, filenames in os.walk(logdir):
    fn_map = dict(((lambda fn: int(fn.split('.')[0][3:]))(fn), fn) for fn in filenames)
    for fid in sorted(fn_map):
        proc = subprocess.Popen(["tail", "-n 24", logdir + "/" + fn_map[fid]], stdout=subprocess.PIPE)
        print "==> msg" + str(fid)
        showedlines = {}
        for line in proc.stdout:
            subparts = map(str.strip, line.split(','))
            for subpart in subparts:
                if subpart.startswith("Average"):
                    showedlines["AL"] = subpart
                elif subpart.startswith("AveQLatency"):
                    showedlines["AQL"] = subpart
        if len(showedlines) == 2:
            t1 = showedlines["AQL"]
            t2 = showedlines["AL"]
            print showedlines["AQL"]
            print showedlines["AL"]
            print float(t2.split()[2].strip("ms")) - float(t1.split()[1].strip("ms"))

            print 
        else:
            print "no enough logs"

