#!/bin/zsh

BASEDIR=`pwd`
KAFKADIR=$BASEDIR/kafka_2.11-0.9.0.1
FLINKDIR=$BASEDIR/flink-1.1.3

jps | grep util-tool-1.0 | cut -d " " -f 1 | xargs kill -9
cd $FLINKDIR
./cancel
sleep 15
cd $KAFKADIR
./stop
sleep 15

