#!/bin/zsh

pid_match() {
   local VAL=`ps -aef | grep "$1" | grep -v grep | awk '{print $2}'`
   echo $VAL
}

start_if_needed() {
  local match="$1"
  shift
  local name="$1"
  shift
  local sleep_time="$1"
  shift
  local PID=`pid_match "$match"`

  if [[ "$PID" -ne "" ]];
  then
    echo "$name is already running..."
  else
    "$@" &
    sleep $sleep_time
  fi
}

stop_if_needed() {
  local match="$1"
  local name="$2"
  local PID=`pid_match "$match"`
  if [[ "$PID" -ne "" ]];
  then
    kill "$PID"
    sleep 1
    local CHECK_AGAIN=`pid_match "$match"`
    if [[ "$CHECK_AGAIN" -ne "" ]];
    then
      kill -9 "$CHECK_AGAIN"
    fi
  else
    echo "No $name instance found to stop"
  fi
}

bin/kafka-topics.sh --delete --zookeeper jkmaster:2181 --topic queue-topic
sleep 3
bin/kafka-topics.sh --delete --zookeeper jkmaster:2181 --topic source-topic
sleep 3
bin/kafka-topics.sh --delete --zookeeper jkmaster:2181 --topic ack-topic
sleep 3
stop_if_needed kafka\.Kafka Kafka
sleep 3
stop_if_needed zookeeper ZooKeeper
sleep 3

rm -rf /tmp/zookeeper/version-2/*
rm -rf /tmp/kafka-logs/
rm -rf logs/*

